import Head from 'next/head';
import Image from 'next/image';

import Header from '../components/Header';
import { useEffect } from 'react';
import { useRouter } from 'next/router';

export default function Home() {

  const router = useRouter();

  useEffect(() => {
    router.push('/articles');
  }, [router]);

  return (
    <>
      <Head>
        <title>Redirecting...</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='bg-gray-100 min-h-screen'>
        <Header />
      </main>
    </>
  );
}
